# Generated by Codex on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activos", "0008_normalizar_prefijos_activos"),
    ]

    operations = [
        migrations.AddField(
            model_name="activo",
            name="codigo_sap",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Codigo SAP unico para laptops y PCs.",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
    ]
