# Generated by Django 6.0.3 on 2026-07-15 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0013_activo_proveedor'),
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='factura_compra',
            field=models.ForeignKey(blank=True, help_text='Factura de compra asociada al activo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='facturas.facturacompra'),
        ),
    ]
