# Generated by Django 6.0.3 on 2026-08-04 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0015_unificar_baja_activos'),
        ('catalogos', '0006_atributoactivo_opcionatributoactivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activo',
            options={'ordering': ['codigo'], 'permissions': [('change_asset_type_controlled', 'Puede cambiar el tipo de un activo con historial')], 'verbose_name': 'Activo', 'verbose_name_plural': 'Activos'},
        ),
        migrations.CreateModel(
            name='ValorAtributoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, default='')),
                ('valor_entero', models.BigIntegerField(blank=True, null=True)),
                ('valor_decimal', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('valor_fecha', models.DateField(blank=True, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('vigente', models.BooleanField(db_index=True, default=True)),
                ('valor_original_migracion', models.TextField(blank=True, default='')),
                ('requiere_revision', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_atributos', to='activos.activo')),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores', to='catalogos.atributoactivo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valores_atributos_creados', to=settings.AUTH_USER_MODEL)),
                ('tipo_activo_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores_atributos_originados', to='catalogos.tipoactivo')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valores_atributos_modificados', to=settings.AUTH_USER_MODEL)),
                ('valor_opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='valores', to='catalogos.opcionatributoactivo')),
            ],
            options={
                'verbose_name': 'Valor de atributo de activo',
                'verbose_name_plural': 'Valores de atributos de activos',
                'ordering': ['activo', 'atributo__nombre'],
                'indexes': [models.Index(fields=['atributo', 'valor_entero'], name='activos_val_atribut_d69f4e_idx'), models.Index(fields=['atributo', 'valor_decimal'], name='activos_val_atribut_fe0b90_idx'), models.Index(fields=['atributo', 'valor_fecha'], name='activos_val_atribut_a742ac_idx'), models.Index(fields=['atributo', 'valor_booleano'], name='activos_val_atribut_495c98_idx')],
                'constraints': [models.UniqueConstraint(fields=('activo', 'atributo'), name='unique_valor_atributo_por_activo')],
            },
        ),
    ]
