# Generated by Django 6.0.3 on 2026-08-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0019_activo_modalidad_tenencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoactivo',
            name='verificado_ti',
            field=models.BooleanField(default=False, help_text="Marca si el activo ya fue revisado por TIC's", verbose_name='Verificado por Ti'),
        ),
    ]
