# Generated by Django 6.0.3 on 2026-08-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0020_eventoactivo_verificado_ti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoactivo',
            name='verificado_ti',
        ),
        migrations.AddField(
            model_name='activo',
            name='verificado_ti',
            field=models.BooleanField(default=False, help_text='Marca si el activo ya fue revisado fisicamente por TI.', verbose_name='Verificado por TI'),
        ),
    ]
