# Generated by Django 6.0.3 on 2026-08-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0021_remove_eventoactivo_verificado_ti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='verificado_ti',
            field=models.BooleanField(default=False, help_text="Marca si el activo ya fue revisado por el departamento de TIC'S", verbose_name="Verificado por TIc's"),
        ),
    ]
