# Generated by Django 6.0.3 on 2026-07-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0003_centrocosto"),
        ("colaboradores", "0003_colaborador_centro_costo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="centro_costo",
            field=models.ForeignKey(
                blank=True,
                help_text="CECO contable vigente del colaborador. Se copia a cada asignación al crearla.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="colaboradores",
                to="catalogos.centrocosto",
            ),
        ),
    ]
