# Generated by Django 6.0.3 on 2026-08-04 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(db_index=True, max_length=80)),
                ('objeto_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('modificar', 'Modificar'), ('activar', 'Activar'), ('desactivar', 'Desactivar'), ('asociar', 'Asociar'), ('cambiar_tipo', 'Cambiar tipo'), ('migrar', 'Migrar'), ('consultar_sensible', 'Consultar informacion sensible')], db_index=True, max_length=24)),
                ('resumen', models.CharField(max_length=255)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-created_at', '-id'],
                'permissions': [('view_attribute_configuration_audit', 'Puede ver auditoria de atributos configurables')],
            },
        ),
    ]
