# Generated by Django 6.0.3 on 2026-08-04 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_alter_empresa_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clave', models.SlugField(help_text='Clave estable en minusculas, sin espacios. No cambia al editar el nombre.', max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_dato', models.CharField(choices=[('texto_corto', 'Texto corto'), ('texto_largo', 'Texto largo'), ('entero', 'Numero entero'), ('decimal', 'Numero decimal'), ('fecha', 'Fecha'), ('booleano', 'Si / No'), ('lista', 'Lista de opciones')], max_length=20)),
                ('unidad', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atributos_activo_creados', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atributos_activo_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atributo de activo',
                'verbose_name_plural': 'Atributos de activos',
                'ordering': ['nombre', 'clave'],
                'permissions': [('manage_asset_attribute_schema', 'Puede administrar atributos configurables')],
            },
        ),
        migrations.CreateModel(
            name='OpcionAtributoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(max_length=80)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opciones', to='catalogos.atributoactivo')),
            ],
            options={
                'verbose_name': 'Opcion de atributo',
                'verbose_name_plural': 'Opciones de atributos',
                'ordering': ['atributo', 'orden', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('atributo', 'clave'), name='unique_clave_opcion_por_atributo')],
            },
        ),
        migrations.CreateModel(
            name='TipoActivoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatorio', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('valor_predeterminado', models.JSONField(blank=True, null=True)),
                ('texto_ayuda', models.CharField(blank=True, max_length=255)),
                ('unidad', models.CharField(blank=True, max_length=30)),
                ('mostrar_detalle', models.BooleanField(default=True)),
                ('mostrar_actas', models.BooleanField(default=False)),
                ('mostrar_reportes', models.BooleanField(default=False)),
                ('filtrable', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('longitud_maxima', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('validaciones', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_tipo', to='catalogos.atributoactivo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_atributos_creadas', to=settings.AUTH_USER_MODEL)),
                ('tipo_activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_atributos', to='catalogos.tipoactivo')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_atributos_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuracion de atributo por tipo',
                'verbose_name_plural': 'Configuraciones de atributos por tipo',
                'ordering': ['tipo_activo', 'orden', 'atributo__nombre'],
                'constraints': [models.UniqueConstraint(fields=('tipo_activo', 'atributo'), name='unique_atributo_por_tipo_activo'), models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('tipo_activo', 'orden'), name='unique_orden_activo_por_tipo')],
            },
        ),
    ]
