# Generated by Django 6.0.3 on 2026-08-04 19:02

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_configuracion_inicial_atributos_activos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='atributoactivo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_nombre_atributo_ci'),
        ),
    ]
