# Generated by Django 6.0.3 on 2026-07-27 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACTIVO_CREADO', 'Activo creado'), ('ACTIVO_CAMBIADO', 'Activo modificado'), ('ACTIVO_BAJA', 'Activo dado de baja'), ('ASIGNACION_CREADA', 'Asignación creada'), ('ASIGNACION_CAMBIADA', 'Asignación modificada'), ('ASIGNACION_FINALIZADA', 'Asignación finalizada'), ('PROVEEDOR_CREADO', 'Proveedor creado'), ('PROVEEDOR_CAMBIADO', 'Proveedor modificado'), ('FACTURA_CREADA', 'Factura creada'), ('FACTURA_CAMBIADA', 'Factura modificada')], max_length=28)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=280)),
                ('entidad_tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('ASIGNACION', 'Asignación'), ('PROVEEDOR', 'Proveedor'), ('FACTURA', 'Factura'), ('NINGUNA', 'Sin entidad')], default='NINGUNA', max_length=16)),
                ('entidad_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ruta', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_generadas', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at', '-id'],
                'permissions': [('view_all_notificacion', 'Puede consultar el historial administrativo de notificaciones')],
                'indexes': [models.Index(fields=['destinatario', 'read_at', '-created_at'], name='notif_dest_read_created_idx'), models.Index(fields=['destinatario', '-created_at'], name='notif_dest_created_idx'), models.Index(fields=['tipo'], name='notif_tipo_idx'), models.Index(fields=['-created_at'], name='notif_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('destinatario', 'fingerprint'), name='unique_notif_dest_fingerprint')],
            },
        ),
    ]
