# Generated by Django 6.0.3 on 2026-07-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_renombrar_notificacion_activo_eliminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('ACTIVO_CREADO', 'Activo creado'), ('ACTIVO_CAMBIADO', 'Activo modificado'), ('ACTIVO_ELIMINADO', 'Activo eliminado'), ('ASIGNACION_CREADA', 'Asignación creada'), ('ASIGNACION_CAMBIADA', 'Asignación modificada'), ('ASIGNACION_FINALIZADA', 'Asignación finalizada'), ('PROVEEDOR_CREADO', 'Proveedor creado'), ('PROVEEDOR_CAMBIADO', 'Proveedor modificado'), ('FACTURA_CREADA', 'Factura creada'), ('FACTURA_CAMBIADA', 'Factura modificada'), ('ASSET_DEPRECIATION_WARNING', 'Alerta de depreciación'), ('ASSET_USEFUL_LIFE_COMPLETED', 'Vida útil cumplida'), ('ASSET_DEPRECIATED_REMINDER', 'Recordatorio de activo depreciado')], max_length=28),
        ),
    ]
