# Generated by Django 6.0.3 on 2026-08-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0006_actaentrega_devolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaentrega',
            name='checksum_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='emitida',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='instantanea_datos',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
