# Generated by Django 6.0.3 on 2026-07-15 16:28

import apps.facturas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0005_alter_empresa_options'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(db_index=True, max_length=80)),
                ('fecha_emision', models.DateField(db_index=True)),
                ('archivo', models.FileField(max_length=255, storage=apps.facturas.models.almacenamiento_facturas, upload_to=apps.facturas.models.ruta_factura)),
                ('nombre_original', models.CharField(editable=False, max_length=255)),
                ('tamano_original', models.PositiveBigIntegerField(default=0, editable=False)),
                ('tamano_almacenado', models.PositiveBigIntegerField(default=0, editable=False)),
                ('estado_compresion', models.CharField(choices=[('comprimido', 'Comprimido'), ('sin_reduccion', 'Original ya optimizado'), ('firma_digital', 'Original conservado por firma digital'), ('fallo_compresion', 'Original conservado por fallo de optimizacion')], default='sin_reduccion', editable=False, max_length=24)),
                ('checksum_sha256', models.CharField(db_index=True, editable=False, max_length=64)),
                ('numero_paginas', models.PositiveIntegerField(default=0, editable=False)),
                ('observaciones', models.TextField(blank=True)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_cargadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_compra', to='catalogos.empresa')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Factura de compra',
                'verbose_name_plural': 'Facturas de compra',
                'ordering': ['-fecha_emision', '-id'],
                'permissions': [('associate_facturacompra', 'Puede asociar o desvincular activos de facturas'), ('download_facturacompra', 'Puede visualizar o descargar facturas'), ('replace_facturacompra', 'Puede reemplazar el PDF de una factura'), ('archive_facturacompra', 'Puede archivar o activar facturas')],
            },
        ),
        migrations.CreateModel(
            name='ReemplazoDocumentoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_anterior', models.FileField(max_length=255, storage=apps.facturas.models.almacenamiento_facturas, upload_to=apps.facturas.models.ruta_factura_historica)),
                ('checksum_anterior', models.CharField(max_length=64)),
                ('archivo_nuevo', models.CharField(max_length=255)),
                ('checksum_nuevo', models.CharField(max_length=64)),
                ('motivo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reemplazos', to='facturas.facturacompra')),
                ('reemplazado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reemplazos_factura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reemplazo de documento de factura',
                'verbose_name_plural': 'Reemplazos de documentos de factura',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EventoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=80)),
                ('accion', models.CharField(choices=[('creacion', 'Creacion'), ('edicion', 'Edicion de metadatos'), ('asociacion', 'Actualizacion de activos asociados'), ('reemplazo', 'Reemplazo de documento'), ('estado', 'Cambio de estado'), ('eliminacion', 'Eliminacion')], max_length=20)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='facturas.facturacompra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_factura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de factura',
                'verbose_name_plural': 'Eventos de facturas',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='facturacompra',
            constraint=models.UniqueConstraint(fields=('proveedor', 'numero_factura', 'empresa'), name='factura_unica_proveedor_numero_empresa'),
        ),
    ]
