# Generated by Django 6.0.3 on 2026-07-27 17:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0015_unificar_baja_activos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlertasDepreciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerta_previa_meses', models.PositiveIntegerField(default=3, help_text='Meses calendario antes de cumplir los 36 meses de vida útil.')),
                ('frecuencia_recordatorio_meses', models.PositiveIntegerField(default=6, help_text='Frecuencia de recordatorios después de cumplir la vida útil.', validators=[django.core.validators.MinValueValidator(1)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de alertas de depreciación',
                'verbose_name_plural': 'Configuración de alertas de depreciación',
                'permissions': [('configure_alertas_depreciacion', 'Puede configurar alertas de depreciación')],
            },
        ),
        migrations.CreateModel(
            name='EventoNotificacionDepreciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ASSET_DEPRECIATION_WARNING', 'Alerta previa'), ('ASSET_USEFUL_LIFE_COMPLETED', 'Vida útil cumplida'), ('ASSET_DEPRECIATED_REMINDER', 'Recordatorio posterior')], max_length=40)),
                ('fecha_programada', models.DateField(db_index=True)),
                ('destinatarios', models.PositiveIntegerField(default=0)),
                ('omitido', models.BooleanField(default=False, help_text='Evento histórico omitido para evitar envíos masivos atrasados.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_notificacion_depreciacion', to='activos.activo')),
            ],
            options={
                'verbose_name': 'Evento de notificación de depreciación',
                'verbose_name_plural': 'Eventos de notificación de depreciación',
                'ordering': ['-fecha_programada', '-id'],
                'indexes': [models.Index(fields=['fecha_programada', 'tipo'], name='depreciacio_fecha_p_290666_idx')],
                'constraints': [models.UniqueConstraint(fields=('activo', 'tipo', 'fecha_programada'), name='unique_evento_depreciacion_programado')],
            },
        ),
    ]
