# Generated by Django 6.0.3 on 2026-07-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depreciacion', '0002_crear_configuracion_alertas_compatibilidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionalertasdepreciacion',
            options={'permissions': [('configure_alertas_depreciacion', 'Puede configurar alertas de depreciación')], 'verbose_name': 'Configuración de depreciación', 'verbose_name_plural': 'Configuración de depreciación'},
        ),
        migrations.AddField(
            model_name='configuracionalertasdepreciacion',
            name='mostrar_valor_residual',
            field=models.BooleanField(default=False, help_text='Muestra el valor residual en el bloque de depreciación del detalle de cada activo.', verbose_name='Mostrar valor residual'),
        ),
    ]
